import time

def funcionsecreta():
    print("If there's anything you need")
    time.sleep(2)
    print("All you have to do is say")
    time.sleep(2)
    print("You know you satisfy everything in me")
    time.sleep(2)
    print("We shouldn't waste a single day")
    time.sleep(2)
    print("So don't stop me falling")
    time.sleep(2)
    print("It's destiny calling")
    time.sleep(2)
    print("A power I just can't deny")
    time.sleep(2)
    print("It's never changing")
    time.sleep(2)
    print("Can't you hear me, I'm saying")
    time.sleep(2)
    print("I want you for the rest of my life")
    time.sleep(2)
    print("Together forever and never to part")
    time.sleep(2)
    print("Together forever we two")
    time.sleep(2)
    print("And don't you know")
    time.sleep(2)
    print("I would move heaven and earth")
    time.sleep(2)
    print("To be together forever with you")
    time.sleep(2)
    print("If they ever get you down")
    time.sleep(2)
    print("There's always something I can do")
    time.sleep(2)
    print("Because I wouldn't ever wanna see you frown")
    time.sleep(2)
    print("I'll always do what's best for you")
    time.sleep(2)
    print("There ain't no mistaking")
    time.sleep(2)
    print("It's true love we're making")
    time.sleep(2)
    print("Something to last for all time")
    time.sleep(2)
    print("It's never changing")
    time.sleep(2)
    print("Can't you hear me, I'm saying")
    time.sleep(2)
    print("I want you for the rest of my life")
    time.sleep(2)
    print("Together forever and never to part")
    time.sleep(2)
    print("Together forever we two")
    time.sleep(2)
    print("And don't you know")
    time.sleep(2)
    print("I would move heaven and earth")
    time.sleep(2)
    print("To be together forever with you")
    time.sleep(2)
    print("So don't stop me falling")
    time.sleep(2)
    print("It's destiny calling")
    time.sleep(2)
    print("A power I just can't deny")
    time.sleep(2)
    print("It's never changing")
    time.sleep(2)
    print("Can't you hear me, I'm saying")
    time.sleep(2)
    print("I want you for the rest of my life")
    time.sleep(2)
    print("Together forever and never to part")
    time.sleep(2)
    print("Together forever we two")
    time.sleep(2)
    print("And don't you know")
    time.sleep(2)
    print("I would move heaven and earth")
    time.sleep(2)
    print("To be together forever with you")
    time.sleep(2)
    print("Together forever and never to part")
    time.sleep(2)
    print("Together forever we two")
    time.sleep(2)
    print("And don't you know")
    time.sleep(2)
    print("I would move heaven and earth")
    time.sleep(2)
    print("To be together forever with you")
    time.sleep(2)
    print("Together forever and never to part")
    time.sleep(2)
    print("Together forever we two")
    time.sleep(2)
    print("And don't you know")
    time.sleep(2)
    print("I would move heaven and earth")
    time.sleep(2)
    print("To be together forever with you")